// Engine verification: the Node port must reproduce the Python reference
// implementation (itself verified cell-for-cell against the dealership's
// Simple_Calculator_2026.xlsx) exactly. vectors.json holds every row of the
// original workbook plus edge cases, generated by the Python oracle.

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');

const { priceUnit, excelRound, mileageDiscount } = require('../lib/pricing');

const vectors = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'vectors.json'), 'utf8'));
const settings = vectors.settings;

const close = (a, b) => {
  if (a === null || a === undefined) return b === null || b === undefined;
  return Math.abs(a - b) < 1e-6;
};

test('excelRound rounds half away from zero', () => {
  assert.strictEqual(excelRound(408.5), 409);
  assert.strictEqual(excelRound(408.4), 408);
  assert.strictEqual(excelRound(-2.5), -3);
});

test('discount chart uses range lookup', () => {
  const chart = settings.discount_chart;
  assert.strictEqual(mileageDiscount(chart, 0), 0);
  assert.strictEqual(mileageDiscount(chart, 3999), 0);
  assert.strictEqual(mileageDiscount(chart, 4000), 800);
  assert.strictEqual(mileageDiscount(chart, 14237), 5900);
  assert.strictEqual(mileageDiscount(chart, 20000), 6900);
});

test(`all ${vectors.primaryRows.length} workbook rows match the oracle exactly`, () => {
  const failures = [];
  for (const { input, expected } of vectors.primaryRows) {
    const unit = priceUnit({
      stockNumber: input.stock,
      model: input.model,
      color: '',
      odometer: input.odometer,
      listPrice: input.listPrice,
      salesCost: input.salesCost,
      msrp: input.msrp,
    }, settings, { miles: input.odometer });

    const checks = [
      ['status', unit.status === expected.status],
      ['invoice', close(unit.invoice, expected.invoice)],
      ['avp', close(unit.avp, expected.avp)],
      ['mileageAdj', close(unit.mileageAdj, expected.mileageAdj)],
      ['salePrice', close(unit.salePrice, expected.salePrice)],
      ['term', unit.term === expected.term],
      ['residualAmount', close(unit.residualAmount, expected.residualAmount)],
      ['leasePayment', unit.leasePayment === expected.leasePayment],
      ['profit', close(unit.profit, expected.profit)],
    ];
    for (const [field, ok] of checks) {
      if (!ok) failures.push(`${input.stock} ${field}: got ${JSON.stringify(unit[field])}, want ${JSON.stringify(expected[field])}`);
    }
  }
  assert.deepStrictEqual(failures, []);
});

test('edge cases match the oracle', () => {
  const failures = [];
  for (const { name, input, expected } of vectors.edgeCases) {
    const unit = priceUnit({
      stockNumber: input.stock,
      model: input.model,
      color: '',
      odometer: input.odometer,
      listPrice: input.listPrice,
      salesCost: input.salesCost,
      msrp: input.msrp,
    }, settings, { tsdMiles: input.tsdMiles ?? null });

    if (unit.status !== expected.status) failures.push(`${name} status: ${unit.status} != ${expected.status}`);
    if (unit.odometer !== expected.milesUsed) failures.push(`${name} milesUsed: ${unit.odometer} != ${expected.milesUsed}`);
    if (unit.mileageUpdated !== expected.mileageUpdated) failures.push(`${name} mileageUpdated: ${unit.mileageUpdated} != ${expected.mileageUpdated}`);
    if (!close(unit.salePrice, expected.salePrice)) failures.push(`${name} salePrice: ${unit.salePrice} != ${expected.salePrice}`);
    if (unit.leasePayment !== expected.leasePayment) failures.push(`${name} leasePayment: ${unit.leasePayment} != ${expected.leasePayment}`);
  }
  assert.deepStrictEqual(failures, []);
});
